language: ruby
rvm:
  - 2.4.2
script:
  - bundle exec rspec
services:
  - postgresql
env:
  global:
    - CC_TEST_REPORTER_ID=e486b5bdc202369e6b85941e8b49ad59e95d54330902f9596ff5ed01c62a7b16
before_script:
  - psql -c 'create database agile_library_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
